title: Smoothieware Documentation
baseurl: ""
source: ./docs

# GitHub Pages theme
remote_theme: pages-themes/midnight@v0.2.0

# Enable GitHub Pages compatible plugins
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-github-metadata

# Process markdown files without front matter
optional_front_matter:
  enabled: true

# Convert relative links
relative_links:
  enabled: true
  collections: false

# Extract titles from headings
titles_from_headings:
  enabled: true
  strip_title: false

# Set default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Include additional directories
include:
  - _pages

# Exclude files from processing
exclude:
  - README.md
  - CLAUDE.md
  - LICENSE
  - tasks/
  - serve-local.sh
  - Gemfile
  - Gemfile.lock
